<?php

/**
 * Block editor (gutenberg) specific functionality
 *
 */ 


/**
 * General (non-block-dependent) editor scripts and styles
 * script changes taxonomy selectors
 * 
 */  


function kapital_enqueue_editor_content_assets() {
    $template_directory = get_template_directory_uri();
    $block_editor_path = $template_directory . '/block-editor/build/';
    $custom_editor_scripts_assets = require dirname(__FILE__) . '/build/custom-editor-scripts/index.asset.php';
    if ( is_admin() ) {
        wp_enqueue_script(
            'custom-editor-scripts',
            $block_editor_path . 'custom-editor-scripts/index.js',  $custom_editor_scripts_assets['dependencies'], $custom_editor_scripts_assets['version']
        );
       wp_enqueue_style( 'styles', $template_directory . '/editor_styles.css?' . filemtime( get_stylesheet_directory() . '/editor_styles.css' ), [], null );
    }
}


/**
 * Add inline svg to gutenberg editor, so that icons are erndered correctly
 * Hook into the 'admin_notices' action to render
 */
function kapital_block_editor_inline_svg() {
    $screen = get_current_screen();
    // Only render this notice in the post editor.
    if ( ! $screen || 'post' !== $screen->base ) {
        return;
    }
    // Render the notice's HTML.
    // with a 'notice' class.
    get_template_part('template-parts/inline-svg-icons');
};
add_action( 'admin_notices', 'kapital_block_editor_inline_svg' );


add_action( 'enqueue_block_editor_assets', 'kapital_enqueue_editor_content_assets' );

/**
 * Block editor (gutenberg) color palette synced from sass
 *
 */

add_action('after_setup_theme', 'kapital_block_editor_setup');

function kapital_block_editor_setup()
{
    $color_palette = generate_color_palette();
    if ($color_palette) {
        add_theme_support('editor-color-palette', $color_palette);
    }
}


/**
 * Checks for our JSON file of color values. If exists, creates a color palette array.
 *
 *
 * @return array
 */
function generate_color_palette()
{
    $color_palette = array();
    // Grabs the autogenerated color palette that we're pulling from our compiled bootstrap stylesheets.
    $file_path = dirname(__FILE__) . '/custom-color-palette.json';
    $color_palette_json = file_get_contents($file_path); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
    if ($color_palette_json) {
        $color_palette_json = json_decode($color_palette_json, true, 512);
        foreach ($color_palette_json["variables"][0]["mapValue"] as $color) {
                $color_palette[] = array(
                    'name'  => $color["name"],
                    'slug'  => $color["name"],
                    'color' => $color["compiledValue"],
                );
        }  
    }
    return $color_palette;
}

//add_filter( 'block_type_metadata', 'set_image_auto_wide' );

function set_image_auto_wide( $metadata ) {
  //var_dump($metadata["name"]);
  //var_dump($metadata);
  if ( "core/image" == $metadata['name'] ) {
    $metadata['attributes']['className']['default'] = "alignwide";
    $metadata['attributes']['align']['default'] = "alignwide";   
    return $metadata;
    //var_dump($metadata['attributes']);
  }
  //var_dump($metadata);
  return $metadata;
}



/** Require all blocks
 */

 require_once(dirname(__FILE__) . '/build/blocks/secondary-title/index.php');
 require_once(dirname(__FILE__) . '/build/blocks/perex/index.php');
 require_once(dirname(__FILE__) . '/build/blocks/ad/index.php');
 require_once(dirname(__FILE__) . '/build/blocks/post-query/index.php');
 require_once(dirname(__FILE__) . '/build/blocks/featured-post/index.php');
 require_once(dirname(__FILE__) . '/build/blocks/podcast-links/index.php');
 require_once(dirname(__FILE__) . '/build/blocks/sponsors/index.php');
 require_once(dirname(__FILE__) . '/build/block-variations/button.php');